# ---------------------------------------------------------------------------
# junk2.py
# Created on: Tue Sep 14 2010 10:39:55 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create(9.3)

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Set workspace:
gp.workspace = "Database Connections\plss.sde"


# Local variables...
#PLSS_TBLFLD_CHASESILI_1000146565 = "true"
#PLSS_TBLFLD_CHASESILI_1000146565__2_ = "Database Connections\\plss.sde\\PLSS.TBLFLD_CHASESILI_1000146565"

# Create list of geodatabase tables:
tables = gp.ListTables('TBLFLD_*')
print tables

# Process: Delete...
#gp.Delete_management(PLSS_TBLFLD_CHASESILI_1000146565__2_, "Table")


# Delete geodatabase tables:
#try:
	#for table in tables:
		#gp.Delete_management(table, "Table")
		#print table
		#table = tables.Next()
#except:
	#print.gp.GetMessages()

